FIX import statement for SMAC>0.13
automl/CAVE pull request #294
Opened 2020-12-15 17:09 UTC by KEggensperger

Should be merged together with https://github.com/automl/ParameterImportance/pull/130

2020-12-19 10:56 UTC, shukon requested changes
Looks good except for requirements, though I didn't run it yet. Will try to in the next week. Could also try to not break backwards-compatibility, but not sure if that's necessary at all (don't know the context CAVE is used atm)

2020-12-19 10:56 UTC, shukon commented on requirements.txt
> +smac>=0.13.0
smac is already mentioned in line 3

2020-12-21 08:04 UTC, KEggensperger commented on requirements.txt
> +smac>=0.13.0
Sorry, I fixed this.

2021-01-31 11:41 UTC, shukon commented
@KEggensperger do you want me to merge this here and in automl/ParameterImportance#130 ? Or is someone responsible for these packages?

2021-03-26 16:12 UTC, AndreBiedenkapp approved these changes
Thanks for taking the time to making it work :)

2021-03-26 16:14 UTC, merged